# Generated by Django 3.2.12 on 2022-05-21 20:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('classroom_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rolename', models.CharField(max_length=30)),
                ('ActivityTypes', models.ManyToManyField(related_name='ActivityType', to='classroom_management.Activity_type')),
                ('RolePermission', models.ManyToManyField(to='classroom_management.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('ppic', models.CharField(max_length=100)),
                ('lastonline', models.DateTimeField()),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='classroom_management.role')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(max_length=100)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.TimeField()),
                ('group', models.IntegerField()),
                ('SessionLead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='classroom_management.staff')),
                ('SessionSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='classroom_management.subject')),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ActivityTypes', to='classroom_management.activity_type')),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='classroom_management.classroom')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='Subjects',
            field=models.ManyToManyField(blank=True, related_name='Subjects', to='classroom_management.Subject'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField()),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('frequency', models.CharField(max_length=5)),
                ('is_finished', models.BooleanField()),
                ('group', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('repetition', models.IntegerField()),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('Classroom', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Classrooms', to='classroom_management.classroom')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RequesterFromStaff', to='classroom_management.staff')),
            ],
        ),
    ]
