# Generated by Django 3.2.12 on 2022-05-22 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0002_auto_20220522_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='activity_id',
        ),
        migrations.AddField(
            model_name='session',
            name='ActivityType',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='SessionActivityTypes', to='classroom_management.activity_type'),
            preserve_default=False,
        ),
    ]
