# Generated by Django 3.2.12 on 2022-05-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0005_remove_staff_activitytypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='ActivityTypes',
            field=models.ManyToManyField(related_name='ActivityType', to='classroom_management.Activity_type'),
        ),
    ]
