# Generated by Django 3.2.12 on 2022-05-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0006_role_activitytypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='Subjects',
            field=models.ManyToManyField(blank=True, related_name='StaffSubjects', to='classroom_management.Subject'),
        ),
    ]
