# Generated by Django 3.2.12 on 2022-05-23 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0007_staff_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='ReqActivityType',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ReqActivityType', to='classroom_management.activity_type'),
        ),
    ]
