# Generated by Django 3.2.12 on 2022-05-23 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0008_request_reqactivitytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='SessionSubject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ssubjects', to='classroom_management.subject'),
        ),
    ]
