# Generated by Django 3.2.12 on 2022-05-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0010_auto_20220523_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='Classroom',
        ),
        migrations.AddField(
            model_name='request',
            name='Classroom',
            field=models.ManyToManyField(blank=True, related_name='RequestClassroom', to='classroom_management.Classroom'),
        ),
    ]
