# Generated by Django 3.2.12 on 2022-05-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0011_auto_20220523_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='Classroom',
            new_name='Classrooms',
        ),
    ]
