# Generated by Django 3.2.12 on 2022-05-23 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0012_rename_classroom_request_classrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='ReqActivityType',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Req_ActivityType', to='classroom_management.activity_type'),
        ),
    ]
