# Generated by Django 3.2.12 on 2022-05-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0014_alter_staff_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='Subjects',
        ),
    ]
