# Generated by Django 3.2.12 on 2022-05-23 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0015_remove_role_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='Classrooms',
        ),
        migrations.AddField(
            model_name='request',
            name='Classrooms',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RequestClassroom', to='classroom_management.classroom'),
            preserve_default=False,
        ),
    ]
