# Generated by Django 3.2.12 on 2022-05-23 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0018_auto_20220523_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='phone_number',
        ),
    ]
