# Generated by Django 3.2.12 on 2022-05-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0019_auto_20220523_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='type',
            field=models.CharField(choices=[('TP', 'TP'), ('TD', 'TD'), ('Amphi', 'Amphi'), ('Other', 'Other')], default='Other', max_length=10),
        ),
    ]
