# Generated by Django 3.2.12 on 2022-05-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0020_alter_classroom_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='is_approved',
            field=models.CharField(choices=[('Approved', 'Approved'), ('On Waiting', 'On Waiting'), ('Desapproved', 'Desapproved')], default='On Waiting', max_length=16),
        ),
    ]
