# Generated by Django 3.2.12 on 2022-05-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0021_alter_request_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='ActivityTypes',
            field=models.ManyToManyField(blank=True, related_name='ActivityType', to='classroom_management.Activity_type'),
        ),
    ]
