# Generated by Django 3.2.12 on 2022-05-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0022_alter_role_activitytypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='request',
            name='repetition',
        ),
        migrations.AlterField(
            model_name='staff',
            name='ppic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
