# Generated by Django 3.2.12 on 2022-05-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0024_alter_request_request_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='group',
            field=models.IntegerField(blank=True),
        ),
    ]
