# Generated by Django 3.2.12 on 2022-05-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0025_alter_request_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='group',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
