# Generated by Django 3.2.12 on 2022-05-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0026_alter_request_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='Rolename',
            new_name='roleName',
        ),
        migrations.RemoveField(
            model_name='role',
            name='RolePermission',
        ),
        migrations.AddField(
            model_name='role',
            name='RolePermission',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='classroom_management.permission'),
            preserve_default=False,
        ),
    ]
