# Generated by Django 3.2.12 on 2022-05-25 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0029_rename_rolename_role_rolename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='RolePermission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom_management.permission'),
        ),
    ]
