# Generated by Django 3.2.12 on 2022-05-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0030_alter_role_rolepermission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='Rolename',
            new_name='roleName',
        ),
    ]
